import { DataTileStyles, FeatureStyleType } from '../map/styles/styles';

export const MaptilerVtStyles: DataTileStyles = {
  water: {
    styleLayerName: 'water',
    sourceLayerName: 'waterStyles',
    hide: false,
    feature: {
      type: FeatureStyleType.polygon,
      color: [
        '$switch',
        ['$get', 'properties.class'],
        ['ocean', ['$rgb', 95, 200, 255]],
        ['dock', ['$rgb', 95, 200, 255]],
        ['river', ['$rgb', 95, 200, 255]],
        ['lake', ['$rgb', 95, 200, 255]],
        ['swimming_pool', ['$rgb', 95, 200, 255]],
        ['$default', ['$rgb', 95, 200, 255]],
      ],
      opacity: 1,
    },
    maxzoom: 15,
    minzoom: 0,
  },
  globallandcover: {
    styleLayerName: 'globallandcover',
    sourceLayerName: 'globallandcoverStyles',
    hide: true,
    feature: {
      type: FeatureStyleType.polygon,
      color: [
        '$switch',
        ['$get', 'properties.class'],
        ['farmland', ['$rgb', 173, 226, 167]],
        ['sand', ['$rgb', 245, 241, 241]],
        ['ice', ['$rgb', 233, 239, 244]],
        ['rock', ['$rgb', 204, 208, 205]],
        ['wood', ['$rgb', 180, 203, 165]],
        ['grass', ['$rgb', 173, 226, 167]],
        ['wetland', ['$rgb', 188, 232, 181]],
        ['crop', ['$rgb', 173, 226, 167]],
        ['scrub', ['$rgb', 238, 234, 231]],
        ['tree', ['$rgb', 194, 228, 187]],
        ['forest', ['$rgb', 194, 228, 187]],
        ['snow', ['$rgb', 233, 239, 244]],
        ['$default', ['$rgb', 173, 226, 167]],
      ],
      hide: [
        '$!',
        [
          '$oneOf',
          ['$get', 'properties.class'],
          'farmland',
          'sand',
          'ice',
          'rock',
          'wood',
          'grass',
          'wetland',
          'crop',
          'scrub',
          'tree',
          'forest',
          'snow',
        ],
      ],
      opacity: 1,
    },
    maxzoom: 9,
    minzoom: 0,
  },
  landcover: {
    styleLayerName: 'landcover',
    sourceLayerName: 'landcoverStyles',
    feature: {
      type: FeatureStyleType.polygon,
      color: [
        '$switch',
        ['$get', 'properties.class'],
        ['farmland', ['$rgb', 173, 226, 167]],
        ['sand', ['$rgb', 245, 241, 241]],
        ['ice', ['$rgb', 233, 239, 244]],
        ['rock', ['$rgb', 204, 208, 205]],
        ['wood', ['$rgb', 180, 203, 165]],
        ['grass', ['$rgb', 173, 226, 167]],
        ['wetland', ['$rgb', 188, 232, 181]],
        ['crop', ['$rgb', 173, 226, 167]],
        ['scrub', ['$rgb', 238, 234, 231]],
        ['tree', ['$rgb', 194, 228, 187]],
        ['forest', ['$rgb', 194, 228, 187]],
        ['snow', ['$rgb', 233, 239, 244]],
        ['$default', ['$rgb', 173, 226, 167]],
      ],
      hide: [
        '$!',
        [
          '$oneOf',
          ['$get', 'properties.class'],
          'farmland',
          'sand',
          'ice',
          'rock',
          'wood',
          'grass',
          'wetland',
          'crop',
          'scrub',
          'tree',
          'forest',
          'snow',
        ],
      ],
      opacity: 1,
    },
    maxzoom: 15,
    minzoom: 0,
  },
  boundary: {
    styleLayerName: 'boundary',
    sourceLayerName: 'boundaryStyles',
    hide: false,
    feature: {
      type: FeatureStyleType.line,
      color: ['$rgb', 114, 113, 207],
    },
    maxzoom: 15,
    minzoom: 0,
  },
  building: {
    styleLayerName: 'building',
    sourceLayerName: 'buildingStyles',
    hide: false,
    feature: {
      type: FeatureStyleType.polygon,
      color: ['$rgb', 222, 215, 211],
    },
    maxzoom: 15,
    minzoom: 13,
  },
  transportation: {
    styleLayerName: 'transportation',
    sourceLayerName: 'transportationStyles',
    hide: false,
    feature: {
      type: FeatureStyleType.line,
      color: [
        '$switch',
        ['$get', 'properties.class'],
        ['primary', ['$rgb', 233, 201, 43]],
        ['secondary', ['$rgb', 233, 201, 43]],
        ['motorway', ['$rgb', 233, 201, 43]],
        ['service', ['$rgb', 215, 218, 226]],
        ['path', ['$rgb', 215, 218, 226]],
        ['minor', ['$rgb', 215, 218, 226]],
      ],
      width: [
        '$switch',
        ['$get', 'properties.class'],
        ['primary', 50],
        ['secondary', 30],
        ['motorway', 30],
        ['service', 30],
        ['path', 30],
        ['minor', 30],
      ],
      hide: [
        '$!',
        ['$oneOf', ['$get', 'properties.class'], 'primary', 'secondary', 'motorway', 'service', 'path', 'minor'],
      ],
    },
    maxzoom: 15,
    minzoom: 4,
  },
  aerodrome_label: {
    styleLayerName: 'aerodrome_label',
    sourceLayerName: 'aerodromeLabelStyles',
    hide: true,
    maxzoom: 15,
    minzoom: 8,
  },
  aeroway: {
    styleLayerName: 'aeroway',
    sourceLayerName: 'aerowayStyles',
    hide: true,
    maxzoom: 15,
    minzoom: 10,
  },
  housenumber: {
    styleLayerName: 'housenumber',
    sourceLayerName: 'housenumberStyles',
    hide: true,
    maxzoom: 15,
    minzoom: 14,
  },
  landuse: {
    styleLayerName: 'landuse',
    sourceLayerName: 'landuseStyles',
    hide: true,
    maxzoom: 15,
    minzoom: 4,
  },
  mountain_peak: {
    styleLayerName: 'mountain_peak',
    sourceLayerName: 'mountain_peakStyles',
    hide: true,
    maxzoom: 15,
    minzoom: 7,
  },
  park: {
    styleLayerName: 'park',
    sourceLayerName: 'parkStyles',
    hide: true,
    maxzoom: 15,
    minzoom: 4,
  },
  place: {
    styleLayerName: 'place',
    sourceLayerName: 'placeStyles',
    hide: true,
    maxzoom: 15,
    minzoom: 0,
  },
  poi: {
    styleLayerName: 'poi',
    sourceLayerName: 'poiStyles',
    hide: true,
    maxzoom: 15,
    minzoom: 12,
  },
  transportation_name: {
    styleLayerName: 'transportation_name',
    sourceLayerName: 'transportation_nameStyles',
    hide: true,
    maxzoom: 15,
    minzoom: 6,
  },
  water_name: {
    styleLayerName: 'water_name',
    sourceLayerName: 'water_nameStyles',
    hide: true,
    maxzoom: 15,
    minzoom: 0,
  },
  waterway: {
    styleLayerName: 'waterway',
    sourceLayerName: 'waterwayStyles',
    hide: true,
    maxzoom: 15,
    minzoom: 3,
  },
};
