import { DataTileStyles, FeatureStyleType } from '../map/styles/styles';

export const VectorStyles: DataTileStyles = {
  water: {
    styleLayerName: 'water',
    sourceLayerName: 'waterStyles',
    feature: {
      type: FeatureStyleType.polygon,
      color: [
        '$switch',
        ['$get', 'properties.class'],
        ['ocean', ['$rgb', 95, 200, 255]],
        ['dock', ['$rgb', 95, 200, 255]],
        ['river', ['$rgb', 95, 200, 255]],
        ['lake', ['$rgb', 95, 200, 255]],
        ['swimming_pool', ['$rgb', 95, 200, 255]],
        ['$default', ['$rgb', 95, 200, 255]],
      ],
    },
    maxzoom: 15,
    minzoom: 0,
  },
  globallandcover: {
    styleLayerName: 'globallandcover',
    sourceLayerName: 'globallandcoverStyles',
    feature: {
      type: FeatureStyleType.polygon,
      color: [
        '$switch',
        ['$get', 'properties.class'],
        ['farmland', ['$rgb', 173, 226, 167]],
        ['sand', ['$rgb', 245, 241, 241]],
        ['ice', ['$rgb', 233, 239, 244]],
        ['rock', ['$rgb', 204, 208, 205]],
        ['wood', ['$rgb', 180, 203, 165]],
        ['grass', ['$rgb', 173, 226, 167]],
        ['wetland', ['$rgb', 188, 232, 181]],
        ['crop', ['$rgb', 173, 226, 167]],
        ['scrub', ['$rgb', 238, 234, 231]],
        ['tree', ['$rgb', 194, 228, 187]],
        ['forest', ['$rgb', 194, 228, 187]],
        ['snow', ['$rgb', 233, 239, 244]],
        ['$default', ['$rgb', 173, 226, 167]],
      ],
      show: [
        '$oneOf',
        ['$get', 'properties.class'],
        'farmland',
        'sand',
        'ice',
        'rock',
        'wood',
        'grass',
        'wetland',
        'crop',
        'scrub',
        'tree',
        'forest',
        'snow',
      ],
    },
    maxzoom: 9,
    minzoom: 0,
  },
  landcover: {
    styleLayerName: 'landcover',
    sourceLayerName: 'landcoverStyles',
    feature: {
      type: FeatureStyleType.polygon,
      color: [
        '$switch',
        ['$get', 'properties.class'],
        ['farmland', ['$rgb', 173, 226, 167]],
        ['sand', ['$rgb', 245, 241, 241]],
        ['ice', ['$rgb', 233, 239, 244]],
        ['rock', ['$rgb', 204, 208, 205]],
        ['wood', ['$rgb', 180, 203, 165]],
        ['grass', ['$rgb', 173, 226, 167]],
        ['wetland', ['$rgb', 188, 232, 181]],
        ['crop', ['$rgb', 173, 226, 167]],
        ['scrub', ['$rgb', 238, 234, 231]],
        ['tree', ['$rgb', 194, 228, 187]],
        ['forest', ['$rgb', 194, 228, 187]],
        ['snow', ['$rgb', 233, 239, 244]],
        ['$default', ['$rgb', 173, 226, 167]],
      ],
      show: [
        '$oneOf',
        ['$get', 'properties.class'],
        'farmland',
        'sand',
        'ice',
        'rock',
        'wood',
        'grass',
        'wetland',
        'crop',
        'scrub',
        'tree',
        'forest',
        'snow',
      ],
    },
    maxzoom: 15,
    minzoom: 0,
  },
  boundary: {
    styleLayerName: 'boundary',
    sourceLayerName: 'boundaryStyles',
    show: false,
    feature: {
      type: FeatureStyleType.line,
      color: ['$rgb', 114, 113, 207],
      show: [
        '$switch',
        ['$get', 'properties.admin_level'],
        [
          2,
          [
            '$if',
            ['$and', ['$gte', ['$get', 'mapState.zoom'], 0], ['$lte', ['$get', 'mapState.zoom'], 2]],
            true,
            false,
          ],
        ],
        [
          3,
          [
            '$if',
            ['$and', ['$gte', ['$get', 'mapState.zoom'], 2], ['$lte', ['$get', 'mapState.zoom'], 3]],
            true,
            false,
          ],
        ],
        [
          4,
          [
            '$if',
            ['$and', ['$gte', ['$get', 'mapState.zoom'], 3], ['$lte', ['$get', 'mapState.zoom'], 4]],
            true,
            false,
          ],
        ],
        [
          5,
          [
            '$if',
            ['$and', ['$gte', ['$get', 'mapState.zoom'], 4], ['$lte', ['$get', 'mapState.zoom'], 5]],
            true,
            false,
          ],
        ],
        [
          6,
          [
            '$if',
            ['$and', ['$gte', ['$get', 'mapState.zoom'], 5], ['$lte', ['$get', 'mapState.zoom'], 6]],
            true,
            false,
          ],
        ],
        [
          7,
          [
            '$if',
            ['$and', ['$gte', ['$get', 'mapState.zoom'], 6], ['$lte', ['$get', 'mapState.zoom'], 7]],
            true,
            false,
          ],
        ],
        [
          8,
          [
            '$if',
            ['$and', ['$gte', ['$get', 'mapState.zoom'], 7], ['$lte', ['$get', 'mapState.zoom'], 8]],
            true,
            false,
          ],
        ],
        [
          9,
          [
            '$if',
            ['$and', ['$gte', ['$get', 'mapState.zoom'], 8], ['$lte', ['$get', 'mapState.zoom'], 9]],
            true,
            false,
          ],
        ],
        [
          10,
          [
            '$if',
            ['$and', ['$gte', ['$get', 'mapState.zoom'], 9], ['$lte', ['$get', 'mapState.zoom'], 20]],
            true,
            false,
          ],
        ],
      ],
    },
    maxzoom: 15,
    minzoom: 0,
  },
  building: {
    styleLayerName: 'building',
    sourceLayerName: 'buildingStyles',
    feature: {
      type: FeatureStyleType.polygon,
      color: ['$rgb', 222, 215, 211],
      minzoom: 15,
    },
  },
  transportation: {
    styleLayerName: 'transportation',
    sourceLayerName: 'transportationStyles',
    show: true,
    feature: {
      type: FeatureStyleType.line,
      color: [
        '$switch',
        ['$get', 'properties.class'],
        ['primary', ['$rgb', 233, 201, 43]],
        ['secondary', ['$rgb', 233, 201, 43]],
        ['motorway', ['$rgb', 233, 201, 43]],
        ['service', ['$rgb', 215, 218, 226]],
        ['path', ['$rgb', 215, 218, 226]],
        ['minor', ['$rgb', 215, 218, 226]],
      ],
      width: [
        '$switch',
        ['$get', 'properties.class'],
        ['primary', 50],
        ['secondary', 30],
        ['motorway', 30],
        ['service', 30],
        ['path', 30],
        ['minor', 30],
      ],
      show: ['$oneOf', ['$get', 'properties.class'], 'primary', 'secondary', 'motorway', 'service', 'path', 'minor'],
    },
    maxzoom: 15,
    minzoom: 4,
  },
  poi: {
    styleLayerName: 'poi',
    sourceLayerName: 'poiStyles',
    show: true,
    feature: {
      type: FeatureStyleType.point,
      radius: 50,
      color: ['$rgb', 250, 185, 57],
      border: {
        type: FeatureStyleType.line,
        color: ['$rgb', 0, 0, 0],
        width: 5,
      },
    },
    maxzoom: 15,
    minzoom: 12,
  },
  aerodrome_label: {
    styleLayerName: 'aerodrome_label',
    sourceLayerName: 'aerodromeLabelStyles',
    show: false,
    maxzoom: 15,
    minzoom: 8,
  },
  aeroway: {
    styleLayerName: 'aeroway',
    sourceLayerName: 'aerowayStyles',
    show: false,
    maxzoom: 15,
    minzoom: 10,
  },
  housenumber: {
    styleLayerName: 'housenumber',
    sourceLayerName: 'housenumberStyles',
    show: false,
    maxzoom: 15,
    minzoom: 14,
  },
  landuse: {
    styleLayerName: 'landuse',
    sourceLayerName: 'landuseStyles',
    show: false,
    maxzoom: 15,
    minzoom: 4,
  },
  mountain_peak: {
    styleLayerName: 'mountain_peak',
    sourceLayerName: 'mountain_peakStyles',
    show: false,
    maxzoom: 15,
    minzoom: 7,
  },
  park: {
    styleLayerName: 'park',
    sourceLayerName: 'parkStyles',
    show: false,
    maxzoom: 15,
    minzoom: 4,
  },
  place: {
    styleLayerName: 'place',
    sourceLayerName: 'placeStyles',
    show: false,
    maxzoom: 15,
    minzoom: 0,
  },
  transportation_name: {
    styleLayerName: 'transportation_name',
    sourceLayerName: 'transportation_nameStyles',
    show: false,
    maxzoom: 15,
    minzoom: 6,
  },
  water_name: {
    styleLayerName: 'water_name',
    sourceLayerName: 'water_nameStyles',
    show: false,
    maxzoom: 15,
    minzoom: 0,
  },
  waterway: {
    styleLayerName: 'waterway',
    sourceLayerName: 'waterwayStyles',
    show: false,
    maxzoom: 15,
    minzoom: 3,
  },
};
