name: Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install modules
      run: npm install
    - name: Run unit tests
      run: npm run test:unit
    - name: Build project for integration tests
      run: npm run test:build
    - name: Run static server
      run: npm run test:server
    - name: Run integration tests
      run: npm run test:integration
